#ifndef DEBUGCALLER_H
#define DEBUGCALLER_H

#include <QObject>
#include "autogenerated/telegramapi.h"
#include "mtproto/dc/dcsessionmanager.h"

class DebugCaller : public QObject
{
    Q_OBJECT

    Q_PROPERTY(QStringList methodList READ methodList CONSTANT FINAL)

    public:
        explicit DebugCaller(QObject *parent = 0);
        QStringList methodList();

    public slots:
        void debugDownload(const QString args);

    private:
        void debugDownload(TLInt dcid, TLLong volumeid, TLInt localid, TLLong secret);
};

#endif // DEBUGCALLER_H
