#include <QApplication>
#include <QQmlApplicationEngine>
#include <autogenerated/telegramqml.h>
#include "qtgram.h"
#include "debugcaller.h"
#include "theme.h"

int main(int argc, char *argv[])
{
    QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
    QApplication app(argc, argv);

    TelegramQml::initialize("LibQTelegram");

    qmlRegisterType<QtGram>("QtGram", 1, 0, "QtGram");
    qmlRegisterType<DebugCaller>("QtGram", 1, 0, "DebugCaller");

    QQmlApplicationEngine engine;

    Theme theme;
    engine.rootContext()->setContextProperty("Theme", &theme);
    engine.load(QUrl(QLatin1String("qml/qtgram.qml")));

    return app.exec();
}
