var countries = [ { text: "Albania", code: "355" },
                  { text: "Algeria", code: "213" },
                  { text: "Andorra", code: "376" },
                  { text: "Angola", code: "244" },
                  { text: "Antigua and Barbuda", code: "-267" },
                  { text: "Argentina", code: "54" },
                  { text: "Armenia", code: "374" },
                  { text: "Australia", code: "61" },
                  { text: "Austria", code: "43" },
                  { text: "Azerbaijan", code: "994" },
                  { text: "The Bahamas", code: "-241" },
                  { text: "Bahrain", code: "973" },
                  { text: "Bangladesh", code: "880" },
                  { text: "Barbados", code: "-245" },
                  { text: "Belarus", code: "375" },
                  { text: "Belgium", code: "32" },
                  { text: "Belize", code: "501" },
                  { text: "Benin", code: "229" },
                  { text: "Bhutan", code: "975" },
                  { text: "Bolivia", code: "591" },
                  { text: "Bosnia and Herzegovina", code: "387" },
                  { text: "Botswana", code: "267" },
                  { text: "Brazil", code: "55" },
                  { text: "Brunei", code: "673" },
                  { text: "Bulgaria", code: "359" },
                  { text: "Burkina Faso", code: "226" },
                  { text: "Burundi", code: "257" },
                  { text: "Cambodia", code: "855" },
                  { text: "Cameroon", code: "237" },
                  { text: "Canada", code: "1" },
                  { text: "Cape Verde", code: "238" },
                  { text: "Central African Republic", code: "236" },
                  { text: "Chad", code: "235" },
                  { text: "Chile", code: "56" },
                  { text: "People's Republic of China", code: "86" },
                  { text: "Colombia", code: "57" },
                  { text: "Comoros", code: "269" },
                  { text: "Congo (Kinshasa)", code: "243" },
                  { text: "Congo (Brazzaville)", code: "242" },
                  { text: "Costa Rica", code: "506" },
                  { text: "Cote d'Ivoire (Ivory Coast)", code: "225" },
                  { text: "Croatia", code: "385" },
                  { text: "Cuba", code: "53" },
                  { text: "Cyprus", code: "357" },
                  { text: "Czech Republic", code: "420" },
                  { text: "Denmark", code: "45" },
                  { text: "Djibouti", code: "253" },
                  { text: "Dominica", code: "-766" },
                  { text: "Dominican Republic (+1-809)", code: "+1-809" },
                  { text: "Dominican Republic (1-829)", code: "1-829" },
                  { text: "Ecuador", code: "593" },
                  { text: "Egypt", code: "20" },
                  { text: "El Salvador", code: "503" },
                  { text: "Equatorial Guinea", code: "240" },
                  { text: "Eritrea", code: "291" },
                  { text: "Estonia", code: "372" },
                  { text: "Ethiopia", code: "251" },
                  { text: "Fiji", code: "679" },
                  { text: "Finland", code: "358" },
                  { text: "France", code: "33" },
                  { text: "Gabon", code: "241" },
                  { text: "The Gambia", code: "220" },
                  { text: "Georgia", code: "995" },
                  { text: "Germany", code: "49" },
                  { text: "Ghana", code: "233" },
                  { text: "Greece", code: "30" },
                  { text: "Grenada", code: "-472" },
                  { text: "Guatemala", code: "502" },
                  { text: "Guinea", code: "224" },
                  { text: "Guinea-Bissau", code: "245" },
                  { text: "Guyana", code: "592" },
                  { text: "Haiti", code: "509" },
                  { text: "Honduras", code: "504" },
                  { text: "Hungary", code: "36" },
                  { text: "Iceland", code: "354" },
                  { text: "India", code: "91" },
                  { text: "Indonesia", code: "62" },
                  { text: "Iran", code: "98" },
                  { text: "Iraq", code: "964" },
                  { text: "Ireland", code: "353" },
                  { text: "Israel", code: "972" },
                  { text: "Italy", code: "39" },
                  { text: "Jamaica", code: "-875" },
                  { text: "Japan", code: "81" },
                  { text: "Jordan", code: "962" },
                  { text: "Kazakhstan", code: "7" },
                  { text: "Kenya", code: "254" },
                  { text: "Kiribati", code: "686" },
                  { text: "North Korea", code: "850" },
                  { text: "South Korea", code: "82" },
                  { text: "Kuwait", code: "965" },
                  { text: "Kyrgyzstan", code: "996" },
                  { text: "Laos", code: "856" },
                  { text: "Latvia", code: "371" },
                  { text: "Lebanon", code: "961" },
                  { text: "Lesotho", code: "266" },
                  { text: "Liberia", code: "231" },
                  { text: "Libya", code: "218" },
                  { text: "Liechtenstein", code: "423" },
                  { text: "Lithuania", code: "370" },
                  { text: "Luxembourg", code: "352" },
                  { text: "Macedonia", code: "389" },
                  { text: "Madagascar", code: "261" },
                  { text: "Malawi", code: "265" },
                  { text: "Malaysia", code: "60" },
                  { text: "Maldives", code: "960" },
                  { text: "Mali", code: "223" },
                  { text: "Malta", code: "356" },
                  { text: "Marshall Islands", code: "692" },
                  { text: "Mauritania", code: "222" },
                  { text: "Mauritius", code: "230" },
                  { text: "Mexico", code: "52" },
                  { text: "Micronesia", code: "691" },
                  { text: "Moldova", code: "373" },
                  { text: "Monaco", code: "377" },
                  { text: "Mongolia", code: "976" },
                  { text: "Montenegro", code: "382" },
                  { text: "Morocco", code: "212" },
                  { text: "Mozambique", code: "258" },
                  { text: "Myanmar (Burma)", code: "95" },
                  { text: "Namibia", code: "264" },
                  { text: "Nauru", code: "674" },
                  { text: "Nepal", code: "977" },
                  { text: "Netherlands", code: "31" },
                  { text: "New Zealand", code: "64" },
                  { text: "Nicaragua", code: "505" },
                  { text: "Niger", code: "227" },
                  { text: "Nigeria", code: "234" },
                  { text: "Norway", code: "47" },
                  { text: "Oman", code: "968" },
                  { text: "Pakistan", code: "92" },
                  { text: "Palau", code: "680" },
                  { text: "Panama", code: "507" },
                  { text: "Papua New Guinea", code: "675" },
                  { text: "Paraguay", code: "595" },
                  { text: "Peru", code: "51" },
                  { text: "Philippines", code: "63" },
                  { text: "Poland", code: "48" },
                  { text: "Portugal", code: "351" },
                  { text: "Qatar", code: "974" },
                  { text: "Romania", code: "40" },
                  { text: "Russia", code: "7" },
                  { text: "Rwanda", code: "250" },
                  { text: "Saint Kitts and Nevis", code: "-868" },
                  { text: "Saint Lucia", code: "-757" },
                  { text: "Saint Vincent and the Grenadines", code: "-783" },
                  { text: "Samoa", code: "685" },
                  { text: "San Marino", code: "378" },
                  { text: "Sao Tome and Principe", code: "239" },
                  { text: "Saudi Arabia", code: "966" },
                  { text: "Senegal", code: "221" },
                  { text: "Serbia", code: "381" },
                  { text: "Seychelles", code: "248" },
                  { text: "Sierra Leone", code: "232" },
                  { text: "Singapore", code: "65" },
                  { text: "Slovakia", code: "421" },
                  { text: "Slovenia", code: "386" },
                  { text: "Solomon Islands", code: "677" },
                  { text: "Somalia", code: "252" },
                  { text: "South Africa", code: "27" },
                  { text: "Spain", code: "34" },
                  { text: "Sri Lanka", code: "94" },
                  { text: "Sudan", code: "249" },
                  { text: "Suriname", code: "597" },
                  { text: "Swaziland", code: "268" },
                  { text: "Sweden", code: "46" },
                  { text: "Switzerland", code: "41" },
                  { text: "Syria", code: "963" },
                  { text: "Tajikistan", code: "992" },
                  { text: "Tanzania", code: "255" },
                  { text: "Thailand", code: "66" },
                  { text: "Timor-Leste (East Timor)", code: "670" },
                  { text: "Togo", code: "228" },
                  { text: "Tonga", code: "676" },
                  { text: "Trinidad and Tobago", code: "-867" },
                  { text: "Tunisia", code: "216" },
                  { text: "Turkey", code: "90" },
                  { text: "Turkmenistan", code: "993" },
                  { text: "Tuvalu", code: "688" },
                  { text: "Uganda", code: "256" },
                  { text: "Ukraine", code: "380" },
                  { text: "United Arab Emirates", code: "971" },
                  { text: "United Kingdom", code: "44" },
                  { text: "United States", code: "1" },
                  { text: "Uruguay", code: "598" },
                  { text: "Uzbekistan", code: "998" },
                  { text: "Vanuatu", code: "678" },
                  { text: "Vatican City", code: "379" },
                  { text: "Venezuela", code: "58" },
                  { text: "Vietnam", code: "84" },
                  { text: "Yemen", code: "967" },
                  { text: "Zambia", code: "260" },
                  { text: "Zimbabwe", code: "263" },
                  { text: "Abkhazia", code: "995" },
                  { text: "Republic of (Taiwan) China", code: "886" },
                  { text: "Nagorno-Karabakh", code: "277" },
                  { text: "Northern Cyprus", code: "-302" },
                  { text: "Pridnestrovie (Transnistria)", code: "-160" },
                  { text: "Somaliland", code: "252" },
                  { text: "South Ossetia", code: "995" },
                  { text: "Christmas Island", code: "61" },
                  { text: "Cocos (Keeling) Islands", code: "61" },
                  { text: "Norfolk Island", code: "672" },
                  { text: "New Caledonia", code: "687" },
                  { text: "French Polynesia", code: "689" },
                  { text: "Mayotte", code: "262" },
                  { text: "Saint Barthelemy", code: "590" },
                  { text: "Saint Martin", code: "590" },
                  { text: "Saint Pierre and Miquelon", code: "508" },
                  { text: "Wallis and Futuna", code: "681" },
                  { text: "Cook Islands", code: "682" },
                  { text: "Niue", code: "683" },
                  { text: "Tokelau", code: "690" },
                  { text: "Guernsey", code: "44" },
                  { text: "Isle of Man", code: "44" },
                  { text: "Jersey", code: "44" },
                  { text: "Anguilla", code: "-263" },
                  { text: "Bermuda", code: "-440" },
                  { text: "British Indian Ocean Territory", code: "246" },
                  { text: "British Sovereign Base Areas", code: "357" },
                  { text: "British Virgin Islands", code: "-283" },
                  { text: "Cayman Islands", code: "-344" },
                  { text: "Falkland Islands (Islas Malvinas)", code: "500" },
                  { text: "Gibraltar", code: "350" },
                  { text: "Montserrat", code: "-663" },
                  { text: "Saint Helena", code: "290" },
                  { text: "Turks and Caicos Islands", code: "-648" },
                  { text: "Northern Mariana Islands", code: "-669" },
                  { text: "Puerto Rico (+1-787)", code: "+1-787" },
                  { text: "Puerto Rico (1-939)", code: "1-939" },
                  { text: "American Samoa", code: "-683" },
                  { text: "Guam", code: "-670" },
                  { text: "U.S. Virgin Islands", code: "-339" },
                  { text: "Hong Kong", code: "852" },
                  { text: "Macau", code: "853" },
                  { text: "Faroe Islands", code: "298" },
                  { text: "Greenland", code: "299" },
                  { text: "French Guiana", code: "594" },
                  { text: "Guadeloupe", code: "590" },
                  { text: "Martinique", code: "596" },
                  { text: "Reunion", code: "262" },
                  { text: "Aland", code: "340" },
                  { text: "Aruba", code: "297" },
                  { text: "Netherlands Antilles", code: "599" },
                  { text: "Svalbard", code: "47" },
                  { text: "Ascension", code: "247" },
                  { text: "Tristan da Cunha", code: "290" } ]
