var countries = [ { text: "Albania", code: "355" },
                  { text: "Algeria", code: "213" },
                  { text: "Andorra", code: "376" },
                  { text: "Angola", code: "244" },
                  { text: "Antigua and Barbuda", code: "-267" },
                  { text: "Argentina", code: "54" },
                  { text: "Armenia", code: "374" },
                  { text: "Australia", code: "61" },
                  { text: "Austria", code: "43" },
                  { text: "Azerbaijan", code: "994" },
                  { text: "The Bahamas", code: "-241" },
                  { text: "Bahrain", code: "973" },
                  { text: "Bangladesh", code: "880" },
                  { text: "Barbados", code: "-245" },
                  { text: "Belarus", code: "375" },
                  { text: "Belgium", code: "32" },
                  { text: "Belize", code: "501" },
                  { text: "Benin", code: "229" },
                  { text: "Bhutan", code: "975" },
                  { text: "Bolivia", code: "591" },
                  { text: "Bosnia and Herzegovina", code: "387" },
                  { text: "Botswana", code: "267" },
                  { text: "Brazil", code: "55" },
                  { text: "Brunei", code: "673" },
                  { text: "Bulgaria", code: "359" },
                  { text: "Burkina Faso", code: "226" },
                  { text: "Burundi", code: "257" },
                  { text: "Cambodia", code: "855" },
                  { text: "Cameroon", code: "237" },
                  { text: "Canada", code: "1" },
                  { text: "Cape Verde", code: "238" },
                  { text: "Central African Republic", code: "236" },
                  { text: "Chad", code: "235" },
                  { text: "Chile", code: "56" },
                  { text: "People's Republic of China", code: "86" },
                  { text: "Colombia", code: "57" },
                  { text: "Comoros", code: "269" },
                  { text: "Congo (Kinshasa)", code: "243" },
                  { text: "Congo (Brazzaville)", code: "242" },
                  { text: "Costa Rica", code: "506" },
                  { text: "Cote d'Ivoire (Ivory Coast)", code: "225" },
                  { text: "Croatia", code: "385" },
                  { text: "Cuba", code: "53" },
                  { text: "Cyprus", code: "357" },
                  { text: "Czech Republic", code: "420" },
                  { text: "Denmark", code: "45" },
                  { text: "Djibouti", code: "253" },
                  { text: "Dominica", code: "-766" },
                  { text: "Dominican Republic (+1-809)", code: "1-809" },
                  { text: "Dominican Republic (1-829)", code: "1-829" },
                  { text: "Ecuador", code: "593" },
                  { text: "Egypt", code: "20" },
                  { text: "El Salvador", code: "503" },
                  { text: "Equatorial Guinea", code: "240" },
                  { text: "Eritrea", code: "291" },
                  { text: "Estonia", code: "372" },
                  { text: "Ethiopia", code: "251" },
                  { text: "Fiji", code: "679" },
                  { text: "Finland", code: "358" },
                  { text: "France", code: "33" },
                  { text: "Gabon", code: "241" },
                  { text: "The Gambia", code: "220" },
                  { text: "Georgia", code: "995" },
                  { text: "Germany", code: "49" },
                  { text: "Ghana", code: "233" },
                  { text: "Greece", code: "30" },
                  { text: "Grenada", code: "-472" },
                  { text: "Guatemala", code: "502" },
                  { text: "Guinea", code: "224" },
                  { text: "Guinea-Bissau", code: "245" },
                  { text: "Guyana", code: "592" },
                  { text: "Haiti", code: "509" },
                  { text: "Honduras", code: "504" },
                  { text: "Hungary", code: "36" },
                  { text: "Iceland", code: "354" },
                  { text: "India", code: "91" },
                  { text: "Indonesia", code: "62" },
                  { text: "Iran", code: "98" },
                  { text: "Iraq", code: "964" },
                  { text: "Ireland", code: "353" },
                  { text: "Israel", code: "972" },
                  { text: "Italy", code: "39" },
                  { text: "Jamaica", code: "-875" },
                  { text: "Japan", code: "81" },
                  { text: "Jordan", code: "962" },
                  { text: "Kazakhstan", code: "7" },
                  { text: "Kenya", code: "254" },
                  { text: "Kiribati", code: "686" },
                  { text: "North Korea", code: "850" },
                  { text: "South Korea", code: "82" },
                  { text: "Kuwait", code: "965" },
                  { text: "Kyrgyzstan", code: "996" },
                  { text: "Laos", code: "856" },
                  { text: "Latvia", code: "371" },
                  { text: "Lebanon", code: "961" },
                  { text: "Lesotho", code: "266" },
                  { text: "Liberia", code: "231" },
                  { text: "Libya", code: "218" },
                  { text: "Liechtenstein", code: "423" },
                  { text: "Lithuania", code: "370" },
                  { text: "Luxembourg", code: "352" },
                  { text: "Macedonia", code: "389" },
                  { text: "Madagascar", code: "261" },
                  { text: "Malawi", code: "265" },
                  { text: "Malaysia", code: "60" },
                  { text: "Maldives", code: "960" },
                  { text: "Mali", code: "223" },
                  { text: "Malta", code: "356" },
                  { text: "Marshall Islands", code: "692" },
                  { text: "Mauritania", code: "222" },
                  { text: "Mauritius", code: "230" },
                  { text: "Mexico", code: "52" },
                  { text: "Micronesia", code: "691" },
                  { text: "Moldova", code: "373" },
                  { text: "Monaco", code: "377" },
                  { text: "Mongolia", code: "976" },
                  { text: "Montenegro", code: "382" },
                  { text: "Morocco", code: "212" },
                  { text: "Mozambique", code: "258" },
                  { text: "Myanmar (Burma)", code: "95" },
                  { text: "Namibia", code: "264" },
                  { text: "Nauru", code: "674" },
                  { text: "Nepal", code: "977" },
                  { text: "Netherlands", code: "31" },
                  { text: "New Zealand", code: "64" },
                  { text: "Nicaragua", code: "505" },
                  { text: "Niger", code: "227" },
                  { text: "Nigeria", code: "234" },
                  { text: "Norway", code: "47" },
                  { text: "Oman", code: "968" },
                  { text: "Pakistan", code: "92" },
                  { text: "Palau", code: "680" },
                  { text: "Panama", code: "507" },
                  { text: "Papua New Guinea", code: "675" },
                  { text: "Paraguay", code: "595" },
                  { text: "Peru", code: "51" },
                  { text: "Philippines", code: "63" },
                  { text: "Poland", code: "48" },
                  { text: "Portugal", code: "351" },
                  { text: "Qatar", code: "974" },
                  { text: "Romania", code: "40" },
                  { text: "Russia", code: "7" },
                  { text: "Rwanda", code: "250" },
                  { text: "Saint Kitts and Nevis", code: "-868" },
                  { text: "Saint Lucia", code: "-757" },
                  { text: "Saint Vincent and the Grenadines", code: "-783" },
                  { text: "Samoa", code: "685" },
                  { text: "San Marino", code: "378" },
                  { text: "Sao Tome and Principe", code: "239" },
                  { text: "Saudi Arabia", code: "966" },
                  { text: "Senegal", code: "221" },
                  { text: "Serbia", code: "381" },
                  { text: "Seychelles", code: "248" },
                  { text: "Sierra Leone", code: "232" },
                  { text: "Singapore", code: "65" },
                  { text: "Slovakia", code: "421" },
                  { text: "Slovenia", code: "386" },
                  { text: "Solomon Islands", code: "677" },
                  { text: "Somalia", code: "252" },
                  { text: "South Africa", code: "27" },
                  { text: "Spain", code: "34" },
                  { text: "Sri Lanka", code: "94" },
                  { text: "Sudan", code: "249" },
                  { text: "Suriname", code: "597" },
                  { text: "Swaziland", code: "268" },
                  { text: "Sweden", code: "46" },
                  { text: "Switzerland", code: "41" },
                  { text: "Syria", code: "963" },
                  { text: "Tajikistan", code: "992" },
                  { text: "Tanzania", code: "255" },
                  { text: "Thailand", code: "66" },
                  { text: "Timor-Leste (East Timor)", code: "670" },
                  { text: "Togo", code: "228" },
                  { text: "Tonga", code: "676" },
                  { text: "Trinidad and Tobago", code: "-867" },
                  { text: "Tunisia", code: "216" },
                  { text: "Turkey", code: "90" },
                  { text: "Turkmenistan", code: "993" },
                  { text: "Tuvalu", code: "688" },
                  { text: "Uganda", code: "256" },
                  { text: "Ukraine", code: "380" },
                  { text: "United Arab Emirates", code: "971" },
                  { text: "United Kingdom", code: "44" },
                  { text: "United States", code: "1" },
                  { text: "Uruguay", code: "598" },
                  { text: "Uzbekistan", code: "998" },
                  { text: "Vanuatu", code: "678" },
                  { text: "Vatican City", code: "379" },
                  { text: "Venezuela", code: "58" },
                  { text: "Vietnam", code: "84" },
                  { text: "Yemen", code: "967" },
                  { text: "Zambia", code: "260" },
                  { text: "Zimbabwe", code: "263" },
                  { text: "Abkhazia", code: "995" },
                  { text: "Republic of (Taiwan) China", code: "886" },
                  { text: "Nagorno-Karabakh", code: "277" },
                  { text: "Northern Cyprus", code: "-302" },
                  { text: "Pridnestrovie (Transnistria)", code: "-160" },
                  { text: "Somaliland", code: "252" },
                  { text: "South Ossetia", code: "995" },
                  { text: "Christmas Island", code: "61" },
                  { text: "Cocos (Keeling) Islands", code: "61" },
                  { text: "Norfolk Island", code: "672" },
                  { text: "New Caledonia", code: "687" },
                  { text: "French Polynesia", code: "689" },
                  { text: "Mayotte", code: "262" },
                  { text: "Saint Barthelemy", code: "590" },
                  { text: "Saint Martin", code: "590" },
                  { text: "Saint Pierre and Miquelon", code: "508" },
                  { text: "Wallis and Futuna", code: "681" },
                  { text: "Cook Islands", code: "682" },
                  { text: "Niue", code: "683" },
                  { text: "Tokelau", code: "690" },
                  { text: "Guernsey", code: "44" },
                  { text: "Isle of Man", code: "44" },
                  { text: "Jersey", code: "44" },
                  { text: "Anguilla", code: "-263" },
                  { text: "Bermuda", code: "-440" },
                  { text: "British Indian Ocean Territory", code: "246" },
                  { text: "British Sovereign Base Areas", code: "357" },
                  { text: "British Virgin Islands", code: "-283" },
                  { text: "Cayman Islands", code: "-344" },
                  { text: "Falkland Islands (Islas Malvinas)", code: "500" },
                  { text: "Gibraltar", code: "350" },
                  { text: "Montserrat", code: "-663" },
                  { text: "Saint Helena", code: "290" },
                  { text: "Turks and Caicos Islands", code: "-648" },
                  { text: "Northern Mariana Islands", code: "-669" },
                  { text: "Puerto Rico (+1-787)", code: "1-787" },
                  { text: "Puerto Rico (1-939)", code: "1-939" },
                  { text: "American Samoa", code: "-683" },
                  { text: "Guam", code: "-670" },
                  { text: "U.S. Virgin Islands", code: "-339" },
                  { text: "Hong Kong", code: "852" },
                  { text: "Macau", code: "853" },
                  { text: "Faroe Islands", code: "298" },
                  { text: "Greenland", code: "299" },
                  { text: "French Guiana", code: "594" },
                  { text: "Guadeloupe", code: "590" },
                  { text: "Martinique", code: "596" },
                  { text: "Reunion", code: "262" },
                  { text: "Aland", code: "340" },
                  { text: "Aruba", code: "297" },
                  { text: "Netherlands Antilles", code: "599" },
                  { text: "Svalbard", code: "47" },
                  { text: "Ascension", code: "247" },
                  { text: "Tristan da Cunha", code: "290" } ];

var codes = { "355"   : "Albania", "213"                           : "Algeria", "376"                          : "Andorra",
              "244"   : "Angola", "-267"                           : "Antigua and Barbuda", "54"               : "Argentina",
              "374"   : "Armenia", "61"                            : "Australia", "43"                         : "Austria",
              "994"   : "Azerbaijan", "-241"                       : "The Bahamas", "973"                      : "Bahrain",
              "880"   : "Bangladesh", "-245"                       : "Barbados", "375"                         : "Belarus",
              "32"    : "Belgium", "501"                           : "Belize", "229"                           : "Benin",
              "975"   : "Bhutan", "591"                            : "Bolivia", "387"                          : "Bosnia and Herzegovina",
              "267"   : "Botswana", "55"                           : "Brazil", "673"                           : "Brunei",
              "359"   : "Bulgaria", "226"                          : "Burkina Faso", "257"                     : "Burundi",
              "855"   : "Cambodia", "237"                          : "Cameroon", "1"                           : "Canada",
              "238"   : "Cape Verde", "236"                        : "Central African Republic", "235"         : "Chad",
              "56"    : "Chile", "86"                              : "People's Republic of China", "57"        : "Colombia",
              "269"   : "Comoros", "243"                           : "Congo (Kinshasa)", "242"                 : "Congo (Brazzaville)",
              "506"   : "Costa Rica", "225"                        : "Cote d'Ivoire (Ivory Coast)", "385"      : "Croatia",
              "53"    : "Cuba", "357"                              : "Cyprus", "420"                           : "Czech Republic",
              "45"    : "Denmark", "253"                           : "Djibouti", "-766"                        : "Dominica",
              "1-809" : "Dominican Republic (+1-809)", "1-829"     : "Dominican Republic (1-829)", "593"       : "Ecuador",
              "20"    : "Egypt", "503"                             : "El Salvador", "240"                      : "Equatorial Guinea",
              "291"   : "Eritrea", "372"                           : "Estonia", "251"                          : "Ethiopia",
              "679"   : "Fiji", "358"                              : "Finland", "33"                           : "France",
              "241"   : "Gabon", "220"                             : "The Gambia", "995"                       : "Georgia",
              "49"    : "Germany", "233"                           : "Ghana", "30"                             : "Greece",
              "-472"  : "Grenada", "502"                           : "Guatemala", "224"                        : "Guinea",
              "245"   : "Guinea-Bissau", "592"                     : "Guyana", "509"                           : "Haiti",
              "504"   : "Honduras", "36"                           : "Hungary", "354"                          : "Iceland",
              "91"    : "India", "62"                              : "Indonesia", "98"                         : "Iran",
              "964"   : "Iraq", "353"                              : "Ireland", "972"                          : "Israel",
              "39"    : "Italy", "-875"                            : "Jamaica", "81"                           : "Japan",
              "962"   : "Jordan", "7"                              : "Kazakhstan", "254"                       : "Kenya",
              "686"   : "Kiribati", "850"                          : "North Korea", "82"                       : "South Korea",
              "965"   : "Kuwait", "996"                            : "Kyrgyzstan", "856"                       : "Laos",
              "371"   : "Latvia", "961"                            : "Lebanon", "266"                          : "Lesotho",
              "231"   : "Liberia", "218"                           : "Libya", "423"                            : "Liechtenstein",
              "370"   : "Lithuania", "352"                         : "Luxembourg", "389"                       : "Macedonia",
              "261"   : "Madagascar", "265"                        : "Malawi", "60"                            : "Malaysia",
              "960"   : "Maldives", "223"                          : "Mali", "356"                             : "Malta",
              "692"   : "Marshall Islands", "222"                  : "Mauritania", "230"                       : "Mauritius",
              "52"    : "Mexico", "691"                            : "Micronesia", "373"                       : "Moldova",
              "377"   : "Monaco", "976"                            : "Mongolia", "382"                         : "Montenegro",
              "212"   : "Morocco", "258"                           : "Mozambique", "95"                        : "Myanmar (Burma)",
              "264"   : "Namibia", "674"                           : "Nauru", "977"                            : "Nepal",
              "31"    : "Netherlands", "64"                        : "New Zealand", "505"                      : "Nicaragua",
              "227"   : "Niger", "234"                             : "Nigeria", "47"                           : "Norway",
              "968"   : "Oman", "92"                               : "Pakistan", "680"                         : "Palau",
              "507"   : "Panama", "675"                            : "Papua New Guinea", "595"                 : "Paraguay",
              "51"    : "Peru", "63"                               : "Philippines", "48"                       : "Poland",
              "351"   : "Portugal", "974"                          : "Qatar", "40"                             : "Romania",
              "7"     : "Russia", "250"                            : "Rwanda", "-868"                          : "Saint Kitts and Nevis",
              "-757"  : "Saint Lucia", "-783"                      : "Saint Vincent and the Grenadines", "685" : "Samoa",
              "378"   : "San Marino", "239"                        : "Sao Tome and Principe", "966"            : "Saudi Arabia",
              "221"   : "Senegal", "381"                           : "Serbia", "248"                           : "Seychelles",
              "232"   : "Sierra Leone", "65"                       : "Singapore", "421"                        : "Slovakia",
              "386"   : "Slovenia", "677"                          : "Solomon Islands", "252"                  : "Somalia",
              "27"    : "South Africa", "34"                       : "Spain", "94"                             : "Sri Lanka",
              "249"   : "Sudan", "597"                             : "Suriname", "268"                         : "Swaziland",
              "46"    : "Sweden", "41"                             : "Switzerland", "963"                      : "Syria",
              "992"   : "Tajikistan", "255"                        : "Tanzania", "66"                          : "Thailand",
              "670"   : "Timor-Leste (East Timor)", "228"          : "Togo", "676"                             : "Tonga",
              "-867"  : "Trinidad and Tobago", "216"               : "Tunisia", "90"                           : "Turkey",
              "993"   : "Turkmenistan", "688"                      : "Tuvalu", "256"                           : "Uganda",
              "380"   : "Ukraine", "971"                           : "United Arab Emirates", "44"              : "United Kingdom",
              "1"     : "United States", "598"                     : "Uruguay", "998"                          : "Uzbekistan",
              "678"   : "Vanuatu", "379"                           : "Vatican City", "58"                      : "Venezuela",
              "84"    : "Vietnam", "967"                           : "Yemen", "260"                            : "Zambia",
              "263"   : "Zimbabwe", "995"                          : "Abkhazia", "886"                         : "Republic of (Taiwan) China",
              "277"   : "Nagorno-Karabakh", "-302"                 : "Northern Cyprus", "-160"                 : "Pridnestrovie (Transnistria)",
              "252"   : "Somaliland", "995"                        : "South Ossetia", "61"                     : "Christmas Island",
              "61"    : "Cocos (Keeling) Islands", "672"           : "Norfolk Island", "687"                   : "New Caledonia",
              "689"   : "French Polynesia", "262"                  : "Mayotte", "590"                          : "Saint Barthelemy",
              "590"   : "Saint Martin", "508"                      : "Saint Pierre and Miquelon", "681"        : "Wallis and Futuna",
              "682"   : "Cook Islands", "683"                      : "Niue", "690"                             : "Tokelau",
              "44"    : "Guernsey", "44"                           : "Isle of Man", "44"                       : "Jersey",
              "-263"  : "Anguilla", "-440"                         : "Bermuda", "246"                          : "British Indian Ocean Territory",
              "357"   : "British Sovereign Base Areas", "-283"     : "British Virgin Islands", "-344"          : "Cayman Islands",
              "500"   : "Falkland Islands (Islas Malvinas)", "350" : "Gibraltar", "-663"                       : "Montserrat",
              "290"   : "Saint Helena", "-648"                     : "Turks and Caicos Islands", "-669"        : "Northern Mariana Islands",
              "1-787" : "Puerto Rico (+1-787)", "1-939"            : "Puerto Rico (1-939)", "-683"             : "American Samoa",
              "-670"  : "Guam", "-339"                             : "U.S. Virgin Islands", "852"              : "Hong Kong",
              "853"   : "Macau", "298"                             : "Faroe Islands", "299"                    : "Greenland",
              "594"   : "French Guiana", "590"                     : "Guadeloupe", "596"                       : "Martinique",
              "262"   : "Reunion", "340"                           : "Aland", "297"                            : "Aruba",
              "599"   : "Netherlands Antilles", "47"               : "Svalbard", "247"                         : "Ascension",
              "290"   : "Tristan da Cunha" };

var index = { "355"   : 0, "213"     : 1, "376"    : 2, "244"    : 3, "-267"   : 4, "54"     : 5,
              "374"   : 6, "61"      : 7, "43"     : 8, "994"    : 9, "-241"   : 10, "973"   : 11,
              "880"   : 12, "-245"   : 13, "375"   : 14, "32"    : 15, "501"   : 16, "229"   : 17,
              "975"   : 18, "591"    : 19, "387"   : 20, "267"   : 21, "55"    : 22, "673"   : 23,
              "359"   : 24, "226"    : 25, "257"   : 26, "855"   : 27, "237"   : 28, "1"     : 29,
              "238"   : 30, "236"    : 31, "235"   : 32, "56"    : 33, "86"    : 34, "57"    : 35,
              "269"   : 36, "243"    : 37, "242"   : 38, "506"   : 39, "225"   : 40, "385"   : 41,
              "53"    : 42, "357"    : 43, "420"   : 44, "45"    : 45, "253"   : 46, "-766"  : 47,
              "1-809" : 48, "1-829"  : 49, "593"   : 50, "20"    : 51, "503"   : 52, "240"   : 53,
              "291"   : 54, "372"    : 55, "251"   : 56, "679"   : 57, "358"   : 58, "33"    : 59,
              "241"   : 60, "220"    : 61, "995"   : 62, "49"    : 63, "233"   : 64, "30"    : 65,
              "-472"  : 66, "502"    : 67, "224"   : 68, "245"   : 69, "592"   : 70, "509"   : 71,
              "504"   : 72, "36"     : 73, "354"   : 74, "91"    : 75, "62"    : 76, "98"    : 77,
              "964"   : 78, "353"    : 79, "972"   : 80, "39"    : 81, "-875"  : 82, "81"    : 83,
              "962"   : 84, "7"      : 85, "254"   : 86, "686"   : 87, "850"   : 88, "82"    : 89,
              "965"   : 90, "996"    : 91, "856"   : 92, "371"   : 93, "961"   : 94, "266"   : 95,
              "231"   : 96, "218"    : 97, "423"   : 98, "370"   : 99, "352"   : 100, "389"  : 101,
              "261"   : 102, "265"   : 103, "60"   : 104, "960"  : 105, "223"  : 106, "356"  : 107,
              "692"   : 108, "222"   : 109, "230"  : 110, "52"   : 111, "691"  : 112, "373"  : 113,
              "377"   : 114, "976"   : 115, "382"  : 116, "212"  : 117, "258"  : 118, "95"   : 119,
              "264"   : 120, "674"   : 121, "977"  : 122, "31"   : 123, "64"   : 124, "505"  : 125,
              "227"   : 126, "234"   : 127, "47"   : 128, "968"  : 129, "92"   : 130, "680"  : 131,
              "507"   : 132, "675"   : 133, "595"  : 134, "51"   : 135, "63"   : 136, "48"   : 137,
              "351"   : 138, "974"   : 139, "40"   : 140, "7"    : 141, "250"  : 142, "-868" : 143,
              "-757"  : 144, "-783"  : 145, "685"  : 146, "378"  : 147, "239"  : 148, "966"  : 149,
              "221"   : 150, "381"   : 151, "248"  : 152, "232"  : 153, "65"   : 154, "421"  : 155,
              "386"   : 156, "677"   : 157, "252"  : 158, "27"   : 159, "34"   : 160, "94"   : 161,
              "249"   : 162, "597"   : 163, "268"  : 164, "46"   : 165, "41"   : 166, "963"  : 167,
              "992"   : 168, "255"   : 169, "66"   : 170, "670"  : 171, "228"  : 172, "676"  : 173,
              "-867"  : 174, "216"   : 175, "90"   : 176, "993"  : 177, "688"  : 178, "256"  : 179,
              "380"   : 180, "971"   : 181, "44"   : 182, "1"    : 183, "598"  : 184, "998"  : 185,
              "678"   : 186, "379"   : 187, "58"   : 188, "84"   : 189, "967"  : 190, "260"  : 191,
              "263"   : 192, "995"   : 193, "886"  : 194, "277"  : 195, "-302" : 196, "-160" : 197,
              "252"   : 198, "995"   : 199, "61"   : 200, "61"   : 201, "672"  : 202, "687"  : 203,
              "689"   : 204, "262"   : 205, "590"  : 206, "590"  : 207, "508"  : 208, "681"  : 209,
              "682"   : 210, "683"   : 211, "690"  : 212, "44"   : 213, "44"   : 214, "44"   : 215,
              "-263"  : 216, "-440"  : 217, "246"  : 218, "357"  : 219, "-283" : 220, "-344" : 221,
              "500"   : 222, "350"   : 223, "-663" : 224, "290"  : 225, "-648" : 226, "-669" : 227,
              "1-787" : 228, "1-939" : 229, "-683" : 230, "-670" : 231, "-339" : 232, "852"  : 233,
              "853"   : 234, "298"   : 235, "299"  : 236, "594"  : 237, "590"  : 238, "596"  : 239,
              "262"   : 240, "340"   : 241, "297"  : 242, "599"  : 243, "47"   : 244, "247"  : 245,
              "290"   : 246 }
